# Site settings
title: Gengue's Blog
email: genesisdaft@gmailn.com
description: > # this means to ignore newlines until "baseurl:"
  Programacion, tecnologia, humor y cosas frikis que nazca contar. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: geneguer
github_username:  gengue

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
